name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1
      - uses: nuget/setup-nuget@v1

      - name: Cache NuGet Packages
        id: cache-nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages/
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          
      - name: Restore NuGet Packages
        if: steps.cache-nuget.outputs.cache-hit != 'true'
        run: |
          nuget restore sc-tools.sln

      - name: Build
        run: |
          msbuild sc-tools.sln -p:Configuration=${{ matrix.config }} -p:Platform=x64 -restore

      - name: Run Tests
        run: |
          dotnet test --no-build -c ${{ matrix.config }} sc-tools.sln

      # TODO: upload artifacts
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name:
      #     path: